version: "3.9"

services:
  app:
    build:
      context: ../service
      dockerfile: Dockerfile
    networks:
      - lab34-net
    mem_limit: "1024m"
    cpus: "2.0"

  nginx:
    image: nginx:alpine
    container_name: lab34-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - lab34-net

  prometheus:
    image: prom/prometheus:latest
    container_name: lab34-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - lab34-net

  grafana:
    image: grafana/grafana:latest
    container_name: lab34-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - lab34-net

networks:
  lab34-net:
    driver: bridge

volumes:
  grafana_data:
