global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "lab56-app"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
