global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "lab910-app1"
    static_configs:
      - targets: ["app1:8000"]

  - job_name: "lab910-app2"
    static_configs:
      - targets: ["app2:8000"]

  - job_name: "lab910-app3"
    static_configs:
      - targets: ["app3:8000"]

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
