version: "3.9"

services:
  app:
    build:
      context: ../service
      dockerfile: Dockerfile
    container_name: lab56-app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL_SECONDS=30
      - CACHE_LOCK_ENABLED=true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - lab56-net

  postgres:
    image: postgres:15-alpine
    container_name: lab56-postgres
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=apppass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lab56-net

  redis:
    image: redis:7-alpine
    container_name: lab56-redis
    ports:
      - "6379:6379"
    networks:
      - lab56-net

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: lab56-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://appuser:apppass@postgres:5432/appdb?sslmode=disable
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - lab56-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: lab56-cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - lab56-net

  prometheus:
    image: prom/prometheus:latest
    container_name: lab56-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - lab56-net

  grafana:
    image: grafana/grafana:latest
    container_name: lab56-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - lab56-net

networks:
  lab56-net:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
